apiVersion: v1
kind: Secret
metadata:
  name: sample-input
type: Opaque
stringData:
  username: admin
  password: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-sample
data:
  sample: |
    fooUser: {{ .sample_input.username }}
    foopassword: {{ .sample_input.password }}
---
apiVersion: kathisto.oconnormi.io/v1beta1
kind: Template
metadata:
  name: template-sample
spec:
  source:
    name: template-sample
  inputs:
    - type: secret
      name: sample-input
  output: sample-output